AWSTemplateFormatVersion: 2010-09-09
Description: >
  Provision a cloudfront distribution for LB and S3 origins

Parameters:
  ProjectName:
    Description: Specify the name of the project
    Type: String
    Default: RediSolar
  ProjectNameSmall:
    Description: Specify the name of the project
    Type: String
    Default: redisolar
  EnvironmentName:
    Description:  The environment in use
    Type: String
    Default: Dev
    AllowedValues:
    - Dev
    - Test
    - Prod
  WorkflowId:
    Description: >
     An ID to uniquely Identifier the resource
     created each time the stack is run
    Type: String
    Default: eee56529-211a-4066-9b2a-a9509536533a
  CertificateARN:
    Description: AWS CM Certificate to be used with cloudfront
    Type: String
  CustomDomainName:
    Description: Custom domian nane to be use with cloudfront
    Type: String
    Default: atoms-energy.com

Resources:
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        IPV6Enabled: False
        Enabled: True
        Aliases:
          - !Sub ${ProjectNameSmall}.${CustomDomainName}
        CacheBehaviors:
          - PathPattern: /
            TargetOriginId:
              Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-${WorkflowId}-WebAppLB
            ViewerProtocolPolicy: allow-all
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            AllowedMethods:
              - GET
              - HEAD
        DefaultCacheBehavior:
          ViewerProtocolPolicy: allow-all
          ForwardedValues:
            QueryString: False
            Cookies:
              Forward: none
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId:
             Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-${WorkflowId}-WebAppLB
        Origins:
          - ConnectionTimeout: 3
            ConnectionAttempts: 2
            DomainName:
              Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-${WorkflowId}-WeBAppLB-DNS
            Id:
               Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-${WorkflowId}-WebAppLB
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginKeepaliveTimeout: 60
              OriginReadTimeout: 5
              OriginProtocolPolicy: http-only
              OriginSSLProtocols:
                - TLSv1
                - TLSv1.1
                - TLSv1.2
                - SSLv3
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateARN
          MinimumProtocolVersion: TLSv1.2_2019
          SslSupportMethod: sni-only
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-CF
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  DistributionID:
    Description: ID of the Destribution
    Value: !Ref Distribution
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-CloudFront-DistributionID

  DistributionDomain:
    Description: Domain Name of the cloudfront distribution
    Value: !GetAtt Distribution.DomainName
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-DistributionDomain
  
  WorkflowId:
    Description: ID to uniquely identify each run of the template.
    Value: !Ref WorkflowId
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-WorkflowId
