AWSTemplateFormatVersion: 2010-09-09
Description: Jump server to serve as administrative interface to the Data center
Parameters:
  ProjectName:
    Description: Project context stack is applied to.
    Type: String
  EnvironmentName:
    Description: The environment context stack is use for.
    Type: String
  PublicCIDR:
    Description: Public CIDR range
    Type: String
    Default: 0.0.0.0/0
  ImageId:
    Description: The Image Id for the server
    Type: String
  InstanceType:
    Description: Instance capability type
    Type: String
  KeyName:
    Description: SSH key name to login to the server
    Type: String  
Resources:
  JumpServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId:
        Fn::ImportValue:
          !Sub ${ProjectName}-${EnvironmentName}-PUB-SN-A
      AvailabilityZone:
        Fn::ImportValue:
          !Sub ${ProjectName}-${EnvironmentName}-PUB-SN-AZ-A
      SecurityGroupIds:
      - Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-JumpServerSG
      SourceDestCheck: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-Jump-Server
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
      UserData:
        Fn::Base64: !Sub |
          #! /bin/bash
          echo Hello world! Jump Server is ready