AWSTemplateFormatVersion: 2010-09-09
Description: Deploy A Redis Server on EC2 instance for Redis Solar
Parameters:
  ProjectName:
    Description: The Project context that the stack is applied to.
    Type: String
    Default: RediSolar
  EnvironmentName: 
    Description: Environment context the stack is applied to
    Type: String
    Default: Dev
    AllowedValues:
    - Dev
    - Test
    - Prod
  ImageId:
    Description: EC2 Image ID to use
    Type: String
    Default: ami-0e999cbd62129e3b1 # us-west-2 (Oregon) Amazon Linux 2 Image
    AllowedValues:
    - ami-0e999cbd62129e3b1 # us-west-2 (Oregon) Amazon Linux 2 AMI
    - ami-03368e982f317ae48 # us-east-1 (N. Virgina) Amazon Linux 2 AMI
  InstanceType:
    Description: Define the capacity of EC2 Image
    Type: String
    Default: t2.micro
  KeyName:
    Description: SSH Key Pair name
    Type: String
    Default: aws2-oregon-key

Resources:
  RedisDBInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId:
        Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-PRI-SN-A
      AvailabilityZone:
        Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-PRI-SN-AZ-A
      # NetworkInterfaces:
      SecurityGroupIds:
      - Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-RedisServerSG
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-Redis-Server
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

      UserData:
        Fn::Base64: !Sub |
          #! /bin/bash
          yum update -y;
          yum install git -y;
          git clone https://github.com/tutugodfrey/redis-solar;
          cd redis-solar;
          ./deploy-redis-with-tls.sh;

Outputs:
  RedisServerPrivateIP:
    Description: Private IP of redis server
    Value:
      Fn::GetAtt: [ RedisDBInstance, PrivateIp ]
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-RedisServer-PRI-IP
