AWSTemplateFormatVersion: 2010-09-09
Description: >
  VPC For Deploying the 
  Application
Parameters:
  ProjectName:
    Description: Project template is been applied to.
    Type: String
    Default: RediSolar
  EnvironmentName:
    Description: An environment name that will be prefixed to resources
    Type: String
    Default: Dev
  VpcCIDR:
    Description: IP range for our VPC (CIDR notation)
    Type: String
    Default: 10.0.0.0/16
  PublicCIDR:
    Type: String
    Default: 0.0.0.0/0
  PublicSubnetACIDR:
    Type: String
    Default: 10.0.5.0/24
  PrivateSubnetACIDR:
    Type: String
    Default: 10.0.2.0/24
  PublicSubnetBCIDR:
    Type: String
    Default: 10.0.20.0/24
  PrivateSubnetBCIDR:
    Type: String
    Default: 10.0.15.0/24
  KeyName:
    Description: ec2 ssh key pair
    Type: String
    Default: aws2-oregon-key
  
Resources:
  moduleVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-VPC
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      VpcId:
        Ref: moduleVPC
      CidrBlock: !Ref PrivateSubnetACIDR
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-PrivateSubnetA
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs '']
      VpcId:
        Ref: moduleVPC
      CidrBlock: !Ref PublicSubnetACIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-PublicSubnetA
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId:
        Ref: moduleVPC
      CidrBlock: !Ref PrivateSubnetBCIDR
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-PrivateSubnetB
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [1, !GetAZs '']
      VpcId:
        Ref: moduleVPC
      CidrBlock: !Ref PublicSubnetBCIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-PublicSubnetB
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  InternetGateWay:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-IGW

  InternetGateWayVPCAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId:
        Ref: InternetGateWay
      VpcId:
        Ref: moduleVPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: moduleVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-public-route-table

  PublicRouteTableAssociationa:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnetA

  PublicRouteTableAssociationb:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnetB

  InternetGatewayPublicRouteAssociation:
    Type: AWS::EC2::Route
    Properties:
      GatewayId:
        Ref: InternetGateWay
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: !Ref PublicCIDR

# To use the highly available configuration for nat instance,
# route table and assocations please comment out this block
# and uncomment the commented route table and subnet association
# in the High Availability sections below

  #  Use one routeable across the two private subnets
  DefaultPrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: moduleVPC
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-default-private-RT

  DefaultPrivateRouteTableAssociationA:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: DefaultPrivateRouteTable
      SubnetId:
        Ref: PrivateSubnetA

  DefaultPrivateRouteTableAssociationB:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: DefaultPrivateRouteTable
      SubnetId:
        Ref: PrivateSubnetB

# The below two route table and subnet association are defined
# to provide a highly available environment in the infrastructure
# For the purpose of cost it is commented out.
# If cost is not a concern uncomment the  block below and
# comment out the routetable and subnet association just above this comment.
# also reference nat-instance-stack.yml for corresponding changes.

# High Availability
  # PrivateRouteTableA:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId:
  #       Ref: moduleVPC
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${ProjectName}-${EnvironmentName}-private-route-table-A

  # PrivateRouteTableAssociation1:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId:
  #       Ref: PrivateRouteTableA
  #     SubnetId:
  #       Ref: PrivateSubnetA

  # PrivateRouteTableB:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId:
  #       Ref: moduleVPC
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${ProjectName}-${EnvironmentName}-private-route-table-B

  # PrivateRouteTableAssociation2:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties:
  #     RouteTableId:
  #       Ref: PrivateRouteTableB
  #     SubnetId:
  #       Ref: PrivateSubnetB

Outputs:
  VPCID:
    Value: !Ref moduleVPC
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-VPCID
  VpcCIDR:
    Value: !Ref VpcCIDR
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-VpcCIDR

  VPCPublicRouteTable:
    Description: Public Routing
    Value: !Ref PublicRouteTable
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PUB-RT

# Uncomment this output if the High Availability
# section in resource definition is in use

# High Availability
  # VPCPrivateRouteTableA:
  #   Description: Private Routing AZ A
  #   Value: !Ref PrivateRouteTableA
  #   Export: 
  #     Name: !Sub ${ProjectName}-${EnvironmentName}-PRI-RT-A
  
  # VPCPrivateRouteTableB:
  #   Description: Private Routing AZ B
  #   Value: !Ref PrivateRouteTableB
  #   Export:
  #     Name: !Sub ${ProjectName}-${EnvironmentName}-PRI-RT-B
  
  # Comment out this section if High Availability section above is in use
  VPCDefaultPrivateRouteTable:
    Description: Route table associated with two private subnets
    Value: !Ref DefaultPrivateRouteTable
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-Default-PRI-RT

  PublicSubnets:
    Description: A list of the public subnets
    Value: !Join [",", [!Ref PublicSubnetA, !Ref PublicSubnetB ]]
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PUB-NETS

  PrivateSubnets:
    Value: !Join [ ",", [!Ref PrivateSubnetA, !Ref PrivateSubnetB ]]
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PRIV-NETS

  PublicSubnetA:
    Description: A reference to Public subnet in 1st AZ
    Value: !Ref PublicSubnetA
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PUB-SN-A

  PublicSubnetB:
    Description: A reference to Public subnet in 2nd AZ
    Value: !Ref PublicSubnetB
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PUB-SN-B

  PrivateSubnetA:
    Description: A reference to Private subnet in 1st AZ
    Value: !Ref PrivateSubnetA
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PRI-SN-A

  PrivateSubnetB:
    Description: A reference to Private subnet in 2nd AZ
    Value: !Ref PrivateSubnetB
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PRI-SN-B

  PublicSubnetAZone:
    Description: Availability zone of the Public subent A
    Value: !GetAtt PublicSubnetA.AvailabilityZone
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PUB-SN-AZ-A
 
  PublicSubnetBZone:
    Description: Availability zone of the Public subent B
    Value:
      Fn::GetAtt: [ PublicSubnetB, AvailabilityZone ]
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PUB-SN-AZ-B

  PrivateSubnetAZone:
    Description: Availability zone of the Private subent A
    Value:
      Fn::GetAtt: [ PrivateSubnetA, AvailabilityZone ]
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PRI-SN-AZ-A

  PrivateSubnetBZone:
    Description: Availability zone of the Private subent B
    Value:
      Fn::GetAtt: [ PrivateSubnetB, AvailabilityZone ]
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PRI-SN-AZ-B

  PublicSubnetACIDR:
    Description: Cidr for Private Subnet A
    Value:
      Ref: PublicSubnetACIDR
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PUB-SN-A-CIDR

  PublicSubnetBCIDR:
    Description: Cidr for Private Subnet B
    Value:
      Ref: PublicSubnetBCIDR
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PUB-SN-B-CIDR

  PrivateSubnetACIDR:
    Description: Cidr for Private Subnet A
    Value:
      Ref: PrivateSubnetACIDR
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PRI-SN-A-CIDR

  PrivateSubnetBCIDR:
    Description: Cidr for Private Subnet B
    Value:
      Ref: PrivateSubnetBCIDR
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-PRI-SN-B-CIDR

