AWSTemplateFormatVersion: 2010-09-09
Description: Deploy A Redis Server on EC2 instance for Redis Solar
Parameters:
  ProjectName:
    Description: The Project context that the stack is applied to.
    Type: String
  EnvironmentName: 
    Description: Environment context the stack is applied to
    Type: String
  ImageId:
    Description: EC2 Image ID to use
    Type: String
  InstanceType:
    Description: Define the capacity of EC2 Image
    Type: String
  KeyName:
    Description: SSH Key Pair name
    Type: String

Resources:
  RedisDBInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SubnetId:
        Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-PRI-SN-A
      AvailabilityZone:
        Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-PRI-SN-AZ-A
      # NetworkInterfaces:
      SecurityGroupIds:
      - Fn::ImportValue: !Sub ${ProjectName}-${EnvironmentName}-RedisServerSG
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName}-Redis-Server
      UserData:
        Fn::Base64: !Sub |
          #! /bin/bash
          yum update -y;
          yum install git -y;
          git clone https://github.com/tutugodfrey/redis-solar;
          cd redis-solar;
          ./deploy-redis-with-tls.sh;

Outputs:
  RedisServerPrivateIP:
    Description: Private IP of redis server
    Value:
      Fn::GetAtt: [ RedisDBInstance, PrivateIp ]
    Export:
      Name: !Sub ${ProjectName}-${EnvironmentName}-RedisServer-PRI-IP
