# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference

version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:13.8.0
  working_directory: ~/redis-solar

# Using my customized centos image packed with redis and node.js installed and configured
noderedis: &noderedis
  docker:
    - image: tutug/node-redis
  working_directory: ~/redis-solar
 

commands:
  destroy_environment:
    steps:
      - run:
          ## Here we want to destroy the infrastructure provisions
          ## However, I am using describe stack for now because the I am still building the infrastructure
          ## And would need to monitor and understand any failure that would occur
          ## would delete from my terminal afterword
          name: Destroy environment when deployment fails
          when: on_fail
          command: |
            # run cloudformation delete_stack command here.
            export TERM=xterm-color
            cd  ./aws-cloud-infra/cloudformation-templates/
            . ./stack-helper.sh
            delete_stack backend-stack${CIRCLE_WORKFLOW_ID};
            sleep 150
            delete_stack loadbalancer-stack${CIRCLE_WORKFLOW_ID};

      - run:
          name: Pipeline Success
          command: |
            echo """
              If you see this message, then the Pipeline has run successfully, Congrate!
              Inspect the workflow to see what the Pipeline does.
            """

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks. 
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.1


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run Lint
          command: npm run lint;

  test:
    <<: *noderedis
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run test
          command: |
            export NODE_TLS_REJECT_UNAUTHORIZED='0'
            /usr/local/bin/redis-server /etc/redis/redis.conf &
            npm test;

  analyze:
    <<: *defaults
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Security Audit with npm audit
          command: |
            echo Pending npm audit;
  
  provision_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Executu CloudFormation template to deploy the infrastructe
          command: |
            export TERM=xterm-color
            cd ./aws-cloud-infra/cloudformation-templates/
            . ./stack-helper.sh
            deploy_stack loadbalancer-stack-${CIRCLE_WORKFLOW_ID} loadbalancer-stack.yml WorkflowId=${CIRCLE_WORKFLOW_ID};
            deploy_stack backend-stack-${CIRCLE_WORKFLOW_ID} backend-stack.yml WorkflowId=${CIRCLE_WORKFLOW_ID};
      - destroy_environment
  
  configure_infrastructure:
    <<: *noderedis
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [YOUR_SSH_FINGER_PRINT_HERE]
      - run:
          name: Run playbook to configure and start the server
          command:
            echo running ansible-playbook -i inventory playbook.yml # work in progress
  
  smoke_test:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Curl the Application to get response
          command: |
            export TERM=xterm-color
            pwd
            export LB_URL=$(aws cloudformation describe-stacks --stack-name loadbalancer-stack --query "Stacks[*].Outputs[?OutputKey=='LoadBalancerDNS'].OutputValue" --output text);
            counter=0;
            echo $LB_URL
            until curl -s --head http://${LB_URL} || [ $counter -gt 20 ]; do
              echo Waiting for application to respond
              sleep 3;
              ((counter++));
            done
      - destroy_environment # Rollback if deployment fails
  
  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout

      - run:
         name: Install Dependencies
         command: |
           yum install -y tar gzip;

      - run:
          name: Get Old WorkflowId
          command: |
            OldWorkflowId=$(aws cloudformation describe-stacks --stack-name redis-solar-cloudfront --query "Stacks[*].Outputs[?OutputKey=='WorkflowId'].OutputValue" --output text);
            echo OldWorkflowId=$OldWorkflowId >> ~/.env;
            echo OLD ID $(cat .env)
      
      - persist_to_workspace:
          root: ~/
          paths:
            - .env
      - run:
          name: Update cloud origin with loadbalancer url
          command: |
            cd ./aws-cloud-infra/cloudformation-templates/
            . ./stack-helper.sh
            deploy_stack redis-solar-cloudfront cloudfront.yml WorkflowId=${CIRCLE_WORKFLOW_ID}

      - destroy_environment # Rollback on failure 

  cleanup_old_environment:
    docker:
      - image: amazon/aws-cli

    steps:
      - checkout

      - run:
         name: Install Dependencies
         command: |
           yum install -y tar gzip;

      - attach_workspace:
          at: ~/
      - run:
          name: clean up
          command: |
            # clean up old environment
            cd ./aws-cloud-infra/cloudformation-templates/
            . ./stack-helper.sh
            export "$(grep OldWorkflowId ~/.env)"
            delete_stack backend-stack-${OldWorkflowId};
            sleep 150
            delete_stack loadbalancer-stack-${OldWorkflowId}

workflows:
  default: 
    jobs:
      - build
      - test:
          requires: [build]
      - analyze:
         requires:  [test]
      - provision_infrastructure:
          requires: [build, test, analyze]
          filters:
            branches:
              only: [develop, add-cloudfront]
      - configure_infrastructure:
          requires: [provision_infrastructure]
      - smoke_test:
          requires: [configure_infrastructure]
      - promote_to_production:
          requires: [smoke_test]
      - cleanup_old_environment:
          requires: [promote_to_production]
